### ISSUE TITLE
Data Set Files Are Not Generating

### ISSUE THREAD

**Issue by USAMACH121** [CollinChaffin/psFitb1t#4]
Hello @CollinChaffin !

Your project is no doubt the best project for getting Heart-Rate data sets for **fitbit** which I ever find.
I have properly installed and configured the setup according to the instruction which you mentioned in documentation. My queries are successfully executing but files are not generating in my module folder, I have tried it several times but still having same problem. I need your help in this issue.
Thanks in advance. :)

Note: Screenshots of Query Execution and Module Folder after the query execution, are attached.

![s1](https://cloud.githubusercontent.com/assets/5113961/14434631/58d7db84-002d-11e6-8ad6-3475b390935e.png)
![s2](https://cloud.githubusercontent.com/assets/5113961/14434632/58d9813c-002d-11e6-9473-2c38e71bc661.png)

**Comment by CollinChaffin** [comment]
That is not the correct install location.  Go to C:\users<username>\Documents\WIndowsPowershell\Modules and give me a screenshot of that psFitb1t folder which is the correct per user install location.  You are clearly running your powershell as Administrator which then uses the wrong module path.  Re-launch powershell (64bit if on 64 bit system) but not specifically as another user (administrator).  Either way, the per user module path is where the module installs - your screenshot clearly shows my module is NOT installed in that system module path.

**Comment by USAMACH121** [comment]
Thank you so much for your quick reply @CollinChaffin . :+1: 

I was making a mistake in finding the generated files into the wrong folder but now I have found that generated file. :dart:
